services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  storage:
    image: redis
    volumes: 
      - ./data:/data
  counter:
    image: aimenin197/counter:0.0.2
    environment:
      - REDIS_URL=redis://storage
    ports:
      - 3002:3002
    depends_on: 
      - storage
  library:
    image: aimenin197/library:0.0.5
    ports:
      - 3000:3000
    depends_on: 
      - storage
      - counter
      - mongo
      - mongo-express