services:
  storage:
    image: redis
    volumes: 
      - ./data:/data
  library:
    build: .
    environment:
      - REDIS_URL=redis://storage
    ports:
      - 3000:3000
    depends_on: 
      - storage