services:
  storage:
    image: redis
    volumes: 
      - ./data:/data
  library:
    image: node:19.4
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=redis://storage
    ports:
      - 80:3000
    working_dir: /app
    command: npm run start
    depends_on: 
      - storage